### ISSUE TITLE
Plugin does not update the model attributes on save

### ISSUE THREAD

**Issue by alex-w0** [mkhanal/knex-case-converter-plugin#2]
When a record will be saved then the save promise doesn't return anymore the model which contains the attributes from the database (id remains undefined...)
```
const response = await Role.forge({
      title: '12',
      active: 1,
    }).save();


ModelBase {
  attributes: [Object: null prototype] { title: '12', active: 1 },
  _previousAttributes: {},
  changed: [Object: null prototype] {},
  relations: {},
  cid: 'c1',
  _knex: null,
  id: undefined
}
```

**Comment by mkhanal** [comment]
Hi, I'm currently not able to maintain the repository. Sorry about that. I plan to get back to it, but it will take quite some time.

Meanwhile, if possible, I recommend to align the db column names to be snake case/camel case if that's what your application uses.

Thank you for understanding.
